name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - math
  - time
  - copy
  - sklearn
  - io
  - datetime
  - ipywidgets
  - prettytable
  - plotly
  - fbProphet
