name: Time-Series-Simulation
channels:
  - intel
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - ipywidgets
  - typing
  - pip:
      - chinesecalendar